### ISSUE TITLE
How to add hashes to renders after upscale or inpaint?

### ISSUE THREAD

**Issue by Adzido** [bluelovers/sd-webui-pnginfo-injection#1]
Hey. I see that this plugin can extract the exact hash of the LoRAs that were used in a given image. What if I use the upscaler and then those hashes disappear, how do I add them to the image again so that CivitAI detects them in “resources”?

**Comment by bluelovers** [comment]
image save on `output/extras-images` is still has pnginfo

only image save from browser is missing
